In [47]:
import pandas as pd

cisfile='ALL_CUSTOMER1205.xlsx'



xl=pd.ExcelFile(cisfile)
xl.sheet_names
if xl.sheet_names[0] == 'ผู้ใช้น้ำทั้งหมด':
    print("ok")
    dtypes={'ประเภท':'category'
            }
    df=pd.read_excel(cisfile,xl.sheet_names[0],dtype=dtypes)

/Users/eakapots/anaconda3/lib/python3.10/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

ok

In [48]:
df

,รหัสหน่วยงาน,เลขที่ผู้ใช้น้ำ,ชื่อผู้ใช้น้ำ,ที่อยู่,ประเภท,การเป็นผู้ใช้น้ำ,สถานภาพการเป็นผู้ใช้น้ำ,สถานะผู้ใช้น้ำ,วันที่เป็นผู้ใช้น้ำ,เงินประกันการใช้น้ำ,...,ย้อนหลัง 5 ด.,ย้อนหลัง 6 ด.,ย้อนหลัง 7 ด.,ย้อนหลัง 8 ด.,ย้อนหลัง 9 ด.,ย้อนหลัง 10 ด.,ย้อนหลัง 11 ด.,ย้อนหลัง 12 ด.,เลขที่ผู้ใช้น้ำมาตรใหญ่,มาตรใหญ่-ย่อย
0,1205,12050000019,น.ส.จันทรา นุ้ยบุตร,261 ม.5 ต.ดอนสัก อ.ดอนสัก จ.สุราษฎร์ธานี 84220,11,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2002-06-07,428.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,มาตรปกติ
1,1205,12050000028,นายสำเริง สายหยุด,16 ม.5 ต.ดอนสัก อ.ดอนสัก จ.สุราษฎร์ธานี 84220,11,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2002-11-06,428.0,...,7.0,6.0,5.0,7.0,6.0,1.0,6.0,1.0,NaN,มาตรปกติ
2,1205,12050000037,นายประเสริฐ โถววรุ่งเรือง,55/3 ม.5 ต.ดอนสัก อ.ดอนสัก จ.สุราษฎร์ธานี 84220,29,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2002-11-06,428.0,...,9.0,12.0,15.0,26.0,29.0,20.0,15.0,14.0,NaN,มาตรปกติ
3,1205,12050000046,น.ส.ทิพย์ไพรวัลย์ ช้างนรินทร์,ม8 ต.กะแดะ อ.กาญจนดิษฐ์ จ.สุราษฎร์ธานี 84160,29,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,1994-09-01,200.0,...,10.0,11.0,8.0,11.0,10.0,7.0,10.0,14.0,NaN,มาตรปกติ
4,1205,12050000055,น.ส.บรรจบ ช้างนรินทร์,28 ต.กะแดะ อ.กาญจนดิษฐ์ จ.สุราษฎร์ธานี 84160,11,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,1994-09-01,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,มาตรปกติ
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14284,1205,12050147261,น.ส.ทิพวรรณ แซ่โค้ว,56/1 ม.4 ต.ตะเคียนทอง อ.กาญจนดิษฐ์ จ.สุราษฎร์ธ...,11,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2021-02-17,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,มาตรปกติ
14285,1205,12050147270,น.ส.คณิฎฐ์ษา แสงทองวรีย์,42/5 ม.6 ต.ตะเคียนทอง อ.กาญจนดิษฐ์ จ.สุราษฎร์ธ...,11,ไม่ได้เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2021-02-19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,มาตรปกติ
14286,1205,12050147289,นางมลดา หมวดเพ็ง,77 ม.1 ต.ปากแพรก อ.ดอนสัก จ.สุราษฎร์ธานี 84220,29,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2021-02-18,535.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,มาตรปกติ
14287,1205,12050147300,น.ส.จามจุรี เสือแก้ว,77/25 ม.2 หมู่บ้านโกเด้นวิว(ปลาทอง) ต.ทุ่งกง อ...,11,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2021-02-18,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,มาตรปกติ
14288,1205,12050147382,น.ส.นิศาชล โต๊ะกลับ,19/13 ม.5 ต.ท่าทองใหม่ อ.กาญจนดิษฐ์ จ.สุราษฎร์...,11,เป็นผู้ใช้น้ำ,ปกติ,ปกติ,2021-02-22,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,มาตรปกติ

In [49]:
df.dtypes

รหัสหน่วยงาน                           int64
เลขที่ผู้ใช้น้ำ                        int64
ชื่อผู้ใช้น้ำ                         object
ที่อยู่                               object
ประเภท                              category
การเป็นผู้ใช้น้ำ                      object
สถานภาพการเป็นผู้ใช้น้ำ               object
สถานะผู้ใช้น้ำ                        object
วันที่เป็นผู้ใช้น้ำ           datetime64[ns]
เงินประกันการใช้น้ำ                  float64
เลขที่ใบเสร็จเงินประกัน               object
วันที่ออกใบเสร็จเงินประกัน    datetime64[ns]
สถานะเงินประกันการใช้น้ำ              object
สิทธิส่วนลด                           object
วันที่ให้สิทธิส่วนลด          datetime64[ns]
วันที่ครบกำหนดสิทธิส่วนลด     datetime64[ns]
ยี่ห้อมาตร                            object
รหัสมาตร                              object
ขนาดมาตร                              object
สภาพมาตร                              object
เส้นทาง                                int64
ลำดับ                                  int64
วันที่อ่านล่าสุด              datetime64[ns]
เลขมาตรล่าสุด                          int64
หน่วยน้ำล่าสุด                       float64
ย้อนหลัง 1 ด.                        float64
ย้อนหลัง 2 ด.                        float64
ย้อนหลัง 3 ด.                        float64
ย้อนหลัง 4 ด.                        float64
ย้อนหลัง 5 ด.                        float64
ย้อนหลัง 6 ด.                        float64
ย้อนหลัง 7 ด.                        float64
ย้อนหลัง 8 ด.                        float64
ย้อนหลัง 9 ด.                        float64
ย้อนหลัง 10 ด.                       float64
ย้อนหลัง 11 ด.                       float64
ย้อนหลัง 12 ด.                       float64
เลขที่ผู้ใช้น้ำมาตรใหญ่              float64
มาตรใหญ่-ย่อย                         object
dtype: object

In [50]:
import sqlite3
conn=sqlite3.connect('info.sqlite3')
c = conn.cursor()
df.to_sql('ALL_CUSTOMER', conn, if_exists='replace', index = False)

14289

In [52]:
import tkinter as tk
tk.filedialog()

AttributeError: module 'tkinter' has no attribute 'filedialog'